/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package psp_ud02_act1.ej6;

import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Vespertino
 */
public class Ej6_GUI extends javax.swing.JFrame {

    /**
     * Creates new form ej1_GUI
     */
    public Ej6_GUI() {
        initComponents();
        initCustom();
    }
    private void initCustom(){
        initPrimerProcesoButton();
        initSegundoProcesoButton();
    }
    
    private void initPrimerProcesoButton(){
        primerProceso.addActionListener((ActionEvent e) -> {
            realizarPrimerProceso();
        });
    }
    
    private void initSegundoProcesoButton(){
        segundoProceso.addActionListener((ActionEvent e) -> {
            realizarSegundoProceso();
        });
    }
    
    private void realizarPrimerProceso() {
        try {
            // Abrir el navegador web
            ProcessBuilder pb = new ProcessBuilder("cmd.exe", "/c", "start", "https://www.google.com");
            pb.start();

            // Mostrar parámetros del proceso
            JOptionPane.showMessageDialog(this, "Proceso 1 iniciado");

            // Matar el proceso
            pb.command("taskkill", "/f", "/im", "chrome.exe");
            pb.start();

            // Notificar la terminación del proceso
            JOptionPane.showMessageDialog(this, "Proceso 1 terminado");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
     private void realizarSegundoProceso() {
        try {
            // Abrir el navegador web
            ProcessBuilder pbNavegador = new ProcessBuilder("cmd.exe", "/c", "start", "https://www.google.com");
            pbNavegador.start();

            // Abrir otro programa (puedes cambiar la ruta y el nombre del programa)
            ProcessBuilder pbPrograma = new ProcessBuilder("notepad.exe");
            pbPrograma.start();

            // Mostrar parámetros de los procesos
            JOptionPane.showMessageDialog(this, "Proceso 2 iniciado");

            // Matar uno de los procesos (en este caso, el navegador)
            pbNavegador.command("taskkill", "/f", "/im", "chrome.exe");
            pbNavegador.start();

            // Notificar la terminación del proceso
            JOptionPane.showMessageDialog(this, "Proceso 2: Navegador terminado");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        primerProceso = new javax.swing.JButton();
        segundoProceso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(400, 100));

        panelPrincipal.setBackground(new java.awt.Color(255, 153, 255));
        panelPrincipal.setMaximumSize(this.getSize()
        );
        panelPrincipal.setPreferredSize(this.getSize()
        );
        panelPrincipal.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        primerProceso.setText("Proceso 1");
        panelPrincipal.add(primerProceso);

        segundoProceso.setText("Proceso 2");
        panelPrincipal.add(segundoProceso);

        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ej6_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ej6_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ej6_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ej6_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ej6_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JButton primerProceso;
    private javax.swing.JButton segundoProceso;
    // End of variables declaration//GEN-END:variables
}
